// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/fsrs.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  MemoryState dco_decode_box_autoadd_memory_state(dynamic raw);

  @protected
  CardStatus dco_decode_card_status(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ItemState dco_decode_item_state(dynamic raw);

  @protected
  MemoryState dco_decode_memory_state(dynamic raw);

  @protected
  MemoryState? dco_decode_opt_box_autoadd_memory_state(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  MemoryState sse_decode_box_autoadd_memory_state(SseDeserializer deserializer);

  @protected
  CardStatus sse_decode_card_status(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ItemState sse_decode_item_state(SseDeserializer deserializer);

  @protected
  MemoryState sse_decode_memory_state(SseDeserializer deserializer);

  @protected
  MemoryState? sse_decode_opt_box_autoadd_memory_state(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_box_autoadd_memory_state(
      MemoryState self, SseSerializer serializer);

  @protected
  void sse_encode_card_status(CardStatus self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_item_state(ItemState self, SseSerializer serializer);

  @protected
  void sse_encode_memory_state(MemoryState self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_memory_state(
      MemoryState? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
