// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

ItemState nextCard(
        {MemoryState? currentMemoryState,
        required int daysElapsed,
        required CardStatus status}) =>
    RustLib.instance.api.crateApiFsrsNextCard(
        currentMemoryState: currentMemoryState,
        daysElapsed: daysElapsed,
        status: status);

enum CardStatus {
  again,
  hard,
  good,
  easy,
  ;
}

class ItemState {
  final MemoryState memory;
  final double interval;

  const ItemState({
    required this.memory,
    required this.interval,
  });

  @override
  int get hashCode => memory.hashCode ^ interval.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ItemState &&
          runtimeType == other.runtimeType &&
          memory == other.memory &&
          interval == other.interval;
}

class MemoryState {
  final double stability;
  final double difficulty;

  const MemoryState({
    required this.stability,
    required this.difficulty,
  });

  @override
  int get hashCode => stability.hashCode ^ difficulty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryState &&
          runtimeType == other.runtimeType &&
          stability == other.stability &&
          difficulty == other.difficulty;
}
